### ISSUE TITLE
Link to PDF version is broken

### ISSUE THREAD

**Issue by bart-roos** [Threat-Modeling-Manifesto/threat-modeling-manifesto#10]
In the *About* section there is a link to the PDF version of the manifesto, but that link seems to be broken and is resulting in a 404 Not Found. I can't really find the PDF elsewhere, so I guess the PDF should be recreated or the link should be removed. 

This is the link location mentioned:

```
https://github.com/Threat-Modeling-Manifesto/threat-modeling-manifesto/releases/latest/download/threat-modeling-manifesto.pdf```

**Comment by johanlindfors** [comment]
This seems to have been fixed now, close this issue?
